import { CategoryName } from '../../../../types/index';

export type FilterOption = {
  key: string;
  value: string;
};

export type Filter = {
  title: string;
  key: string;
  options: FilterOption[];
};

export type CategoryFilterBatch = {
  [key in CategoryName]: { accordion?: Filter[]; switcher?: Filter[] };
};

export const filters: CategoryFilterBatch = {
  CPU: {
    accordion: [
      {
        title: 'Clock Speed',
        key: 'clockSpeed',
        options: [
          { value: '1.5 GHz - 1.99 GHz', key: '1.5-1.9-GHz' },
          { value: '2.0 GHz - 2.49 GHz', key: '2.0-2.4-GHz' },
          { value: '2.5 GHz - 2.99 GHz', key: '2.5-2.9-GHz' },
          { value: '3.0 GHz and higher', key: '3.0-5.0-GHz' },
        ],
      },
      {
        title: 'Lithography',
        key: 'lithography',
        options: [
          { value: '5 nm', key: '5 nm' },
          { value: '7 nm', key: '7 nm' },
          { value: '10 nm', key: '10 nm' },
          { value: '12 nm', key: '12 nm' },
          { value: '14 nm', key: '14 nm' },
          { value: '22 nm', key: '22 nm' },
          { value: '28 nm', key: '28 nm' },
          { value: '32 nm', key: '32 nm' },
          { value: '45 nm', key: '45 nm' },
        ],
      },
      {
        title: 'Socket',
        key: 'socket',
        options: [
          { value: 'AMD AM5', key: 'AMD AM5' },
          { value: 'AMD AM4', key: 'AMD AM4' },
          { value: 'AMD AM3', key: 'AMD AM3' },
          { value: 'AMD AM1', key: 'AMD AM1' },
          { value: 'AMD TR4', key: 'AMD TR4' },
          { value: 'AMD TRX4', key: 'AMD TRX4' },
          { value: 'AMD AM3+', key: 'AMD AM3+' },
          { value: 'AMD FM2', key: 'AMD FM2' },
          { value: 'AMD WRX8', key: 'AMD WRX8' },
          { value: 'AMD SP3', key: 'AMD SP3' },
          { value: 'Intel LGA 1151 v2', key: 'Intel LGA 1151 v2' },
          { value: 'Intel LGA 1200', key: 'Intel LGA 1200' },
          { value: 'Intel LGA 2011', key: 'Intel LGA 2011' },
          { value: 'Intel LGA 2011 v3', key: 'Intel LGA 2011 v3' },
          { value: 'Intel LGA 1700', key: 'Intel LGA 1700' },
          { value: 'Intel LGA 1155', key: 'Intel LGA 1155' },
          { value: 'Intel LGA 1156', key: 'Intel LGA 1156' },
          { value: 'Intel LGA 1151', key: 'Intel LGA 1151' },
          { value: 'Intel LGA 1150', key: 'Intel LGA 1150' },
          { value: 'Intel LGA 3647', key: 'Intel LGA 3647' },
          { value: 'Intel LGA 2066', key: 'Intel LGA 2066' },
        ],
      },
      {
        title: 'Threads Number',
        key: 'threads',
        options: [
          { value: '2 threads', key: '2 threads' },
          { value: '4 threads', key: '4 threads' },
          { value: '6 threads', key: '6 threads' },
          { value: '8 threads', key: '8 threads' },
          { value: '12 threads', key: '12 threads' },
          { value: '16 threads', key: '16 threads' },
          { value: '20 threads', key: '20 threads' },
          { value: '24 threads', key: '24 threads' },
          { value: '32 threads', key: '32 threads' },
          { value: '36 threads', key: '36 threads' },
          { value: '40 threads', key: '40 threads' },
          { value: '48 threads', key: '48 threads' },
          { value: '56 threads', key: '56 threads' },
          { value: '128 threads', key: '128 threads' },
        ],
      },
      {
        title: 'Cores Number',
        key: 'cores',
        options: [
          { value: '2 cores', key: '2 cores' },
          { value: '4 cores', key: '4 cores' },
          { value: '6 cores', key: '6 cores' },
          { value: '8 cores', key: '8 cores' },
          { value: '10 cores', key: '10 cores' },
          { value: '12 cores', key: '12 cores' },
          { value: '14 cores', key: '14 cores' },
          { value: '16 cores', key: '16 cores' },
          { value: '18 cores', key: '18 cores' },
          { value: '20 cores', key: '20 cores' },
          { value: '28 cores', key: '28 cores' },
          { value: '64 cores', key: '64 cores' },
        ],
      },
    ],
    switcher: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'INTEL', key: 'Intel' },
          { value: 'AMD', key: 'AMD' },
        ],
      },
    ],
  },
  GPU: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'Intel', key: 'Intel' },
          { value: 'AMD', key: 'AMD' },
          { value: 'Nvidia', key: 'NVIDIA' },
        ],
      },
      {
        title: 'Vendor',
        key: 'vendor',
        options: [
          { value: 'Asus', key: 'Asus' },
          { value: 'Palit', key: 'Palit' },
          { value: 'Gigabyte', key: 'Gigabyte' },
          { value: 'MSI', key: 'MSI' },
          { value: 'ZOTAC', key: 'ZOTAC' },
          { value: 'PowerColor', key: 'PowerColor' },
          { value: 'Sapphire', key: 'Sapphire' },
          { value: 'INNO3D', key: 'INNO3D' },
          { value: 'XFX', key: 'XFX' },
          { value: 'ASRock', key: 'ASRock' },
          { value: 'EVGA', key: 'EVGA' },
          { value: 'Biostar', key: 'Biostar' },
          { value: 'AFOX', key: 'AFOX' },
        ],
      },
      {
        title: 'Chip',
        key: 'GPUModel',
        options: [
          { value: 'GeForce RTX 3050', key: 'NVIDIA GeForce RTX 3050' },
          { value: 'GeForce RTX 3060', key: 'NVIDIA GeForce RTX 3060' },
          { value: 'GeForce RTX 3060 Ti', key: 'NVIDIA GeForce RTX 3060 Ti' },
          { value: 'GeForce RTX 3070', key: 'NVIDIA GeForce RTX 3070' },
          { value: 'GeForce RTX 3080', key: 'NVIDIA GeForce RTX 3080' },
          { value: 'GeForce GTX 1650', key: 'NVIDIA GeForce GTX 1650' },
          { value: 'GeForce GTX 1050 Ti', key: 'NVIDIA GeForce GTX 1050 Ti' },
          {
            value: 'GeForce GTX 1660 SUPER',
            key: 'NVIDIA GeForce GTX 1660 SUPER',
          },
        ],
      },
      {
        title: 'Memory',
        key: 'memorySize',
        options: [
          { value: '4 GB', key: '4 GB' },
          { value: '6 GB', key: '6 GB' },
          { value: '8 GB', key: '8 GB' },
          { value: '10 GB', key: '10 GB' },
          { value: '12 GB', key: '12 GB' },
          { value: '16 GB', key: '16 GB' },
          { value: '24 GB', key: '24 GB' },
        ],
      },
      {
        title: 'Memory bus',
        key: 'memoryBus',
        options: [
          { value: '128 bit', key: '128 bit' },
          { value: '192 bit', key: '192 bit' },
          { value: '256 bit', key: '256 bit' },
          { value: '320 bit', key: '320 bit' },
          { value: '384 bit', key: '384 bit' },
        ],
      },
      {
        title: 'Memory type',
        key: 'memoryType',
        options: [
          { value: 'GDDR5', key: 'GDDR5' },
          { value: 'GDDR6', key: 'GDDR6' },
          { value: 'GDDR6X', key: 'GDDR6X' },
        ],
      },
      {
        title: 'Number of fans',
        key: 'fans',
        options: [
          { value: '1 fan', key: '1' },
          { value: '2 fans', key: '2' },
          { value: '3 fans', key: '3' },
        ],
      },
    ],
  },
  motherboard: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'Asus', key: 'Asus' },
          { value: 'ASRock', key: 'ASRock' },
          { value: 'Biostar', key: 'Biostar' },
          { value: 'Gigabyte', key: 'Gigabyte' },
          { value: 'MSI', key: 'MSI' },
        ],
      },
      {
        title: 'Socket',
        key: 'socket',
        options: [
          { value: 'AMD AM5', key: 'AMD AM5' },
          { value: 'AMD AM4', key: 'AMD AM4' },
          { value: 'Intel LGA 1200', key: 'Intel LGA 1200' },
          { value: 'Intel LGA 1700', key: 'Intel LGA 1700' },
          { value: 'Intel LGA 1151 v2', key: 'Intel LGA 1151 v2' },
          { value: 'Intel LGA 1151', key: 'Intel LGA 1151' },
        ],
      },
      {
        title: 'Form factor',
        key: 'formFactor',
        options: [
          { value: 'ATX', key: 'ATX' },
          { value: 'Micro-ATX', key: 'micro-ATX' },
          { value: 'Mini-ITX', key: 'mini-ITX' },
        ],
      },
      {
        title: 'Ram type',
        key: 'ramType',
        options: [
          { value: 'DDR4', key: 'DDR4' },
          { value: 'DDR5', key: 'DDR5' },
        ],
      },
      {
        title: 'Max. memory size',
        key: 'maxMemory',
        options: [
          { value: '32 GB', key: '32 GB' },
          { value: '64 GB', key: '64 GB' },
          { value: '128 GB', key: '128 GB' },
        ],
      },
    ],
  },
  RAM: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'A-Data', key: 'A-Data' },
          { value: 'AMD', key: 'AMD' },
          { value: 'Corsair', key: 'Corsair' },
          { value: 'Crucial', key: 'Crucial' },
          { value: 'Dato', key: 'Dato' },
          { value: 'Exceleram', key: 'Exceleram' },
          { value: 'HyperX', key: 'HyperX' },
          { value: 'G.Skill', key: 'G.Skill' },
          { value: 'GOODRAM', key: 'GOODRAM' },
          { value: 'Kingston Fury', key: 'Kingston Fury' },
          { value: 'Patriot Memory', key: 'Patriot Memory' },
          { value: 'Samsung', key: 'Samsung' },
          { value: 'Team Group', key: 'Team Group' },
        ],
      },
      {
        title: 'Ram type',
        key: 'ramType',
        options: [
          { value: 'DDR3', key: 'DDR3' },
          { value: 'DDR4', key: 'DDR4' },
          { value: 'DDR5', key: 'DDR5' },
        ],
      },
      {
        title: 'Capacity',
        key: 'capacity',
        options: [
          { value: '4 GB', key: '4 GB' },
          { value: '8 GB', key: '8 GB' },
          { value: '16 GB', key: '16 GB' },
          { value: '32 GB', key: '32 GB' },
          { value: '64 GB', key: '64 GB' },
        ],
      },
      {
        title: 'Modules',
        key: 'modules',
        options: [
          { value: '1 Stick', key: '1' },
          { value: '2 Sticks', key: '2' },
        ],
      },
      {
        title: 'Speed',
        key: 'speed',
        options: [
          { value: '1333 MHz', key: '1333 MHz' },
          { value: '1600 MHz', key: '1600 MHz' },
          { value: '2400 MHz', key: '2400 MHz' },
          { value: '2666 MHz', key: '2666 MHz' },
          { value: '2800 MHz', key: '2800 MHz' },
          { value: '3000 MHz', key: '3000 MHz' },
          { value: '3200 MHz', key: '3200 MHz' },
          { value: '3600 MHz', key: '3600 MHz' },
          { value: '4000 MHz', key: '4000 MHz' },
          { value: '4400 MHz', key: '4400 MHz' },
          { value: '5200 MHz', key: '5200 MHz' },
          { value: '5600 MHz', key: '5600 MHz' },
          { value: '6000 MHz', key: '6000 MHz' },
          { value: '6400 MHz', key: '6400 MHz' },
          { value: '7200 MHz', key: '7200 MHz' },
          { value: '8000 MHz', key: '8000 MHz' },
        ],
      },
    ],
  },
  HDD: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'Dell', key: 'Dell' },
          { value: 'HP', key: 'HP' },
          { value: 'Hitachi', key: 'Hitachi' },
          { value: 'Lenovo', key: 'Lenovo' },
          { value: 'MediaMax', key: 'MediaMax' },
          { value: 'Seagate', key: 'Seagate' },
          { value: 'Synology', key: 'Synology' },
          { value: 'Toshiba', key: 'Toshiba' },
          { value: 'Western Digital', key: 'WD' },
        ],
      },
      {
        title: 'Form factor',
        key: 'formFactor',
        options: [
          { value: '2.5 "', key: '2.5 "' },
          { value: '3.5 "', key: '3.5 "' },
        ],
      },
      {
        title: 'Capacity',
        key: 'capacity',
        options: [
          { value: '320 GB', key: '320 GB' },
          { value: '500 GB', key: '500 GB' },
          { value: '600 GB', key: '600 GB' },
          { value: '900 GB', key: '900 GB' },
          { value: '1200 GB', key: '1200 GB' },
          { value: '2400 GB', key: '2400 GB' },
          { value: '1 TB', key: '1000 GB' },
          { value: '2 TB', key: '2000 GB' },
          { value: '3 TB', key: '3000 GB' },
          { value: '4 TB', key: '4000 GB' },
          { value: '6 TB', key: '6000 GB' },
          { value: '8 TB', key: '8000 GB' },
          { value: '10 TB', key: '10000 GB' },
          { value: '12 TB', key: '12000 GB' },
          { value: '14 TB', key: '14000 GB' },
          { value: '16 TB', key: '16000 GB' },
          { value: '18 TB', key: '18000 GB' },
          { value: '20 TB', key: '20000 GB' },
        ],
      },
      {
        title: 'Revolutions per minute',
        key: 'RPM',
        options: [
          { value: '4200 RPM', key: '4200 rpm' },
          { value: '5400 RPM', key: '5400 rpm' },
          { value: '5900 RPM', key: '5900 rpm' },
          { value: '7200 RPM', key: '7200 rpm' },
          { value: '5400-7200 RPM', key: '5400-7200 rpm' },
          { value: '10000 RPM', key: '10000 rpm' },
          { value: '15000 RPM', key: '15000 rpm' },
        ],
      },
    ],
  },
  SSD: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'Acer', key: 'Acer' },
          { value: 'A-Data', key: 'A-Data' },
          { value: 'Crucial', key: 'Crucial' },
          { value: 'Gigabyte', key: 'Gigabyte' },
          { value: 'GOODRAM', key: 'GOODRAM' },
          { value: 'HP', key: 'HP' },
          { value: 'Kingston', key: 'Kingston' },
          { value: 'MSI', key: 'MSI' },
          { value: 'Patriot Memory', key: 'Patriot Memory' },
          { value: 'Samsung', key: 'Samsung' },
          { value: 'Transcend', key: 'Transcend' },
          { value: 'Team Group', key: 'Team Group' },
          { value: 'Western Digital', key: 'WD' },
        ],
      },
      {
        title: 'Capacity',
        key: 'capacity',
        options: [
          { value: '240 GB', key: '240 GB' },
          { value: '256 GB', key: '256 GB' },
          { value: '480 GB', key: '480 GB' },
          { value: '500 GB', key: '500 GB' },
          { value: '512 GB', key: '512 GB' },
          { value: '520 GB', key: '520 GB' },
          { value: '960 GB', key: '960 GB' },
          { value: '1024 GB', key: '1024 GB' },
          { value: '2048 GB', key: '2048 GB' },
          { value: '1 TB', key: '1000 GB' },
          { value: '2 TB', key: '2000 GB' },
          { value: '8 TB', key: '8000 GB' },
        ],
      },
      {
        title: 'Form factor',
        key: 'formFactor',
        options: [
          { value: 'M.2', key: 'M.2' },
          { value: '2.5"', key: '2.5"' },
        ],
      },
    ],
  },
  PSU: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'Gamemax', key: 'Gamemax' },
          { value: 'FSP', key: 'FSP' },
          { value: 'Zalman', key: 'Zalman' },
          { value: 'Seasonic', key: 'Seasonic' },
          { value: 'Chieftec', key: 'Chieftec' },
          { value: 'Deepcool', key: 'Deepcool' },
          { value: 'Aerocool', key: 'Aerocool' },
          { value: 'be quiet!', key: 'be quiet!' },
          { value: 'Gigabyte', key: 'Gigabyte' },
          { value: 'Cougar', key: 'Cougar' },
          { value: 'Corsair', key: 'Corsair' },
          { value: 'Asus', key: 'Asus' },
          { value: '1stPlayer', key: '1stPlayer' },
          { value: 'cooler-master', key: 'Cooler Master' },
          { value: 'Silver Stone', key: 'Silver Stone' },
          { value: 'MSI', key: 'MSI' },
          { value: '2E', key: '2E' },
          { value: 'QUBE', key: 'QUBE' },
        ],
      },
      {
        title: 'Cable system',
        key: 'cableSystem',
        options: [
          { value: 'modular', key: 'modular' },
          { value: 'non-modular', key: 'non-modular' },
          { value: 'semi-modular', key: 'semi-modular' },
        ],
      },
      {
        title: 'Power',
        key: 'power',
        options: [
          { value: '500', key: '500' },
          { value: '550', key: '550' },
          { value: '600', key: '600' },
          { value: '650', key: '650' },
          { value: '700', key: '700' },
          { value: '750', key: '750' },
          { value: '850', key: '850' },
          { value: '1000', key: '1000' },
          { value: '1200', key: '1200' },
        ],
      },
      {
        title: 'Form Factor',
        key: 'psuFormFactor',
        options: [
          { value: 'ATX', key: 'ATX' },
          { value: 'SFX', key: 'SFX' },
          { value: 'Flex ATX', key: 'Flex ATX' },
        ],
      },
    ],
  },
  case: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'Chieftec', key: 'Chieftec' },
          { value: 'Gamemax', key: 'Gamemax' },
          { value: 'Fractal Design', key: 'Fractal Design' },
          { value: 'QUBE', key: 'QUBE' },
          { value: 'Deepcool', key: 'Deepcool' },
          { value: 'Zalman', key: 'Zalman' },
          { value: 'Vinga', key: 'Vinga' },
          { value: '2E', key: '2E' },
          { value: 'DarkFlash', key: 'DarkFlash' },
          { value: 'Aerocool', key: 'Aerocool' },
          { value: 'Lian Li', key: 'Lian Li' },
          { value: 'Asus', key: 'Asus' },
          { value: 'Jansbo', key: 'Jansbo' },
          { value: 'NZXT', key: 'NZXT' },
          { value: '1stPlayer', key: '1stPlayer' },
          { value: 'Gamedias', key: 'Gamedias' },
          { value: 'Xilence', key: 'Xilence' },
          { value: 'be quiet!', key: 'be quiet!' },
          { value: 'cooler-master', key: 'Cooler Master' },
          { value: 'Golden Field', key: 'Golden Field' },
          { value: 'Fronteir', key: 'Fronteir' },
        ],
      },
      {
        title: 'Form factor',
        key: 'caseFormFactor',
        options: [
          { value: 'Midi Tower', key: 'Midi Tower' },
          { value: 'Mini Tower', key: 'Mini Tower' },
          { value: 'Full Tower', key: 'Full Tower' },
          { value: 'Desktop', key: 'Desktop' },
          { value: 'Cube Case', key: 'Cube Case' },
        ],
      },
      {
        title: 'PSU Form factor',
        key: 'psuFormFactor',
        options: [
          { value: 'ATX', key: 'ATX' },
          { value: 'SFX', key: 'SFX' },
        ],
      },
      {
        title: 'Motherboard Form factor',
        key: 'formFactor',
        options: [
          { value: 'ATX', key: 'ATX' },
          { value: 'Micro-ATX', key: 'micro-ATX' },
          { value: 'E-ATX', key: 'E-ATX' },
          { value: 'Mini-ITX', key: 'mini-ITX' },
        ],
      },
      {
        title: 'Material',
        key: 'material',
        options: [
          { value: 'Steel', key: 'steel' },
          { value: 'Aluminium', key: 'Aluminium' },
        ],
      },
    ],
  },
  cooling: {
    accordion: [
      {
        title: 'Brand',
        key: 'brand',
        options: [
          { value: 'Deepcool', key: 'Deepcool' },
          { value: 'ID-COOLING', key: 'ID-COOLING' },
          { value: 'be quiet!', key: 'be quiet!' },
          { value: 'QUBE', key: 'QUBE' },
          { value: 'Arctic', key: 'ARCTIC' },
          { value: 'PC Cooler', key: 'PCCooler' },
          { value: 'MSI', key: 'MSI' },
          { value: 'Jansbo', key: 'Jansbo' },
          { value: 'Asus', key: 'Asus' },
          { value: 'Aerocool', key: 'Aerocool' },
          { value: 'Xilence', key: 'Xilence' },
          { value: 'NZXT', key: 'NZXT' },
        ],
      },
      {
        title: 'Socket',
        key: 'socket',
        options: [
          { value: 'AMD AM2', key: 'AMD AM2' },
          { value: 'AMD AM3', key: 'AMD AM3' },
          { value: 'AMD AM4', key: 'AMD AM4' },
          { value: 'AMD AM5', key: 'AMD AM5' },
          { value: 'AMD TRX4', key: 'AMD TRX4' },
          { value: 'AMD FM1', key: 'AMD FM1' },
          { value: 'AMD FM2', key: 'AMD FM2' },
          { value: 'Intel LGA 775', key: 'Intel LGA 775' },
          { value: 'Intel LGA 1366', key: 'Intel LGA 1366' },
          { value: 'Intel LGA 1700', key: 'Intel LGA 1700' },
          { value: 'Intel LGA 2011', key: 'Intel LGA 2011' },
          { value: 'Intel LGA 2011 v3', key: 'Intel LGA 2011 v3' },
          { value: 'Intel LGA 2066', key: 'Intel LGA 2066' },
          { value: 'Intel LGA 1200', key: 'Intel LGA 1200' },
          { value: 'Intel LGA 1155', key: 'Intel LGA 1155' },
          { value: 'Intel LGA 1156', key: 'Intel LGA 1156' },
          { value: 'Intel LGA 1151', key: 'Intel LGA 1151' },
          { value: 'Intel LGA 1151 v2', key: 'Intel LGA 1151 v2' },
        ],
      },
      {
        title: 'Cooling type',
        key: 'type',
        options: [
          { value: 'Active cooler', key: 'active fan' },
          { value: 'Liquid cooling', key: 'liquid cooling' },
        ],
      },
      {
        title: 'Targeting',
        key: 'target',
        options: [{ value: 'For CPU', key: 'for processor' }],
      },
    ],
  },
};
